# include: package:lint/analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_redundant_argument_values: ignore
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    unused_element_parameter: ignore
    # todo: ignore

linter:
  rules:
    # ------- Error Rules ------- #
    avoid_dynamic_calls: false
    prefer_const_literals_to_create_immutables: true
    constant_identifier_names: false
    prefer_if_elements_to_conditional_expressions: false
    avoid_positional_boolean_parameters: false
    use_build_context_synchronously: false
    no_leading_underscores_for_library_prefixes: true
    sort_pub_dependencies: false
    always_use_package_imports: true
    comment_references: false
    use_key_in_widget_constructors: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_single_quotes: true
    avoid_void_async: true
    require_trailing_commas: true
    use_to_and_as_if_applicable: true
    avoid_classes_with_only_static_members: false
    prefer_final_fields: true
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    avoid_print: true
    close_sinks: false
    avoid_catching_errors: true
    unnecessary_statements: true
    hash_and_equals: true
    empty_statements: true
    prefer_typing_uninitialized_variables: true
    type_annotate_public_apis: false
    prefer_is_empty: true
    collection_methods_unrelated_type: true
    prefer_is_not_empty: true
    annotate_overrides: true
    avoid_returning_this: true
    camel_case_extensions: true
    camel_case_types: true
    do_not_use_environment: true
    null_closures: true
    prefer_contains: true
    no_duplicate_case_values: true
    unrelated_type_equality_checks: true
    avoid_function_literals_in_foreach_calls: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    avoid_js_rounded_ints: true
    avoid_private_typedef_functions: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    ## diagnostic_describe_all_properties: true
    ## list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    prefer_relative_imports: false
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    ## use_build_context_synchronously: true (experimental)
    valid_regexps: true
    # ------- Style Rules ------- #
    always_put_required_named_parameters_first: false
    avoid_annotating_with_dynamic: false
    avoid_redundant_argument_values: true
    avoid_implementing_value_types: false
    avoid_init_to_null: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: false
    directives_ordering: true
    flutter_style_todos: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: true
    curly_braces_in_flow_control_structures: true
    non_constant_identifier_names: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_is_not_operator: false
    prefer_mixin: false
    sized_box_for_whitespace: false
    sort_child_properties_last: false
    unawaited_futures: false
    unnecessary_await_in_return: false
    noop_primitive_operations: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    use_decorated_box: false
    use_if_null_to_convert_nulls_to_bools: false
    unnecessary_raw_strings: true
    unnecessary_overrides: true
    avoid_field_initializers_in_const_classes: true
    avoid_multiple_declarations_per_line: true
    use_raw_strings: false # must be true
    unnecessary_string_interpolations: true
    use_string_buffers: true
    unnecessary_const: true
    always_declare_return_types: true
    # always_put_control_body_on_new_line: true
    ## always_specify_types: true
    avoid_bool_literals_in_conditional_expressions: true
    ## avoid_catches_without_on_clauses: true
    ## avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    ## cast_nullable_to_non_nullable: true (experimental)
    conditional_uri_does_not_exist: true
    deprecated_consistency: true
    empty_catches: false # must be true
    empty_constructor_bodies: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    implementation_imports: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: false
    lines_longer_than_80_chars: false
    missing_whitespace_between_adjacent_strings: true
    ## no_default_cases: true (experimental)
    no_runtimeType_toString: true
    null_check_on_nullable_type_parameter: true
    ## one_member_abstracts: true
    overridden_fields: true
    package_prefixed_library_names: true
    parameter_assignments: false
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: false
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_in_for_each: true
    ## prefer_final_parameters: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: false
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: false
    prefer_interpolation_to_compose_strings: true
    prefer_iterable_whereType: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    provide_deprecation_message: true
    public_member_api_docs: false
    recursive_getters: true
    sized_box_shrink_expand: true
    slash_for_doc_comments: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_init_formals: true
    unnecessary_constructor_name: true
    unnecessary_final: false
    unnecessary_getters_setters: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_this: true
    use_colored_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: false
    use_rethrow_when_possible: true
    use_super_parameters: true
    use_test_throws_matchers: true
    void_checks: true
    # ------- Pub Rules ------- #
    depend_on_referenced_packages: false # must be true
    package_names: true
    secure_pubspec_urls: true

dart_code_metrics:
  anti-patterns:
    long-method: true
    long-parameter-list: true
  metrics:
    # cyclomatic-complexity: 20
    # halstead-volume: 150
    # lines-of-code: 100
    # maintainability-index: 50
    # maximum-nesting-level: 5
    # number-of-methods: 10
    # number-of-parameters: 4
    # source-lines-of-code: 50
    # weight-of-class: 0.33
  metrics-exclude:
    - test/**
    - lib/generated/**
  rules:
    prefer-trailing-comma: true
    avoid-ignoring-return-values: true
    ## avoid-late-keyword: true
    avoid-nested-conditional-expressions: true
    avoid-non-null-assertion: true
    avoid-unused-parameters: true
    binary-expression-operand-order: true
    double-literal-format: true
    member-ordering: true
    newline-before-return: true
    no-boolean-literal-compare: true
    no-empty-block: true
    no-equal-arguments: true
    no-equal-then-else: true
    no-magic-number: true
    no-object-declaration: true
    prefer-conditional-expressions: true
    prefer-correct-identifier-length: true
    prefer-correct-type-name: true
    prefer-first: true
    prefer-last: true
    prefer-match-file-name: true
    always-remove-listener: true
    ## avoid-returning-widgets: true
    avoid-unnecessary-setstate: true
    avoid-wrapping-in-padding: true
    prefer-const-border-radius: true
    prefer-extracting-callbacks: true
    prefer-single-widget-per-file: true
