name: flutterexam
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  flutter_modular: any
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  skeletonizer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: any
  flutter_flavorizr: ^2.2.3
  retrofit_generator: any
  dart_mappable_builder: any
  flutter_gen_runner: any
  mocktail: any
  bloc_test: any
  analyzer: ^7.3.0

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
